### ISSUE TITLE
Text copied from keyboard select when Keyboard select is disabled

### ISSUE THREAD

**Issue by cborisa** [dinhani/vscode-copy-on-select#2]
I have disabled copy to clipboard on keyboard select, however when I select part of the text together with "CTRL" key (to jump to the next group), it gets also copied to clipboard. 
Not sure if this is somehow related to issue https://github.com/Microsoft/vscode/issues/30230, but could have at least similar cause
My VSCODE is 1.21.0, 
OS: Windows 10

**Comment by dinhani** [comment]
This issue should be fixed in the newest releast (0.0.6).

It seems the problem was with `TextEditorSelectionChangeEvent::kind` property.

When you select words holding CTRL, the `kind` property is `undefined`, and I did not foresee that. The function that checks if the text should be copied was defaulting to true instead of false for the unforeseen cases.
